############################
#  TG-SHOP  docker-compose #
############################

services:
  ##################################################################
  # PostgreSQL
  ##################################################################
  postgres:
    image: postgres:15
    container_name: psgr
    restart: always
    env_file:
      - .env                       # POSTGRES_DB / USER / PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg-shop-net

  ##################################################################
  # Django + Gunicorn
  ##################################################################
  web:
    build: ./shop_tg_app          # Dockerfile in /shop_tg_app/DockerFile
    image: hurtki/tg-shop:latest
    container_name: django
    restart: always
    env_file:
      - .env                      
    depends_on:
      - postgres
      - redis
    networks:
      - tg-shop-net           
    volumes:
      - ./shop_tg_app/static:/app/www/shop_tg_app/static
      - ./shop_tg_app/media:/app/www/shop_tg_app/media
  ##################################################################
  # Nginx (80 → web:8000)
  ##################################################################
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - web
    networks:
      - tg-shop-net
    ports:
      - "80:80"
    volumes:
      - ./nginx/tg-shop.nossl.conf:/etc/nginx/conf.d/tg-shop.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf
      - ./shop_tg_app/static:/app/www/shop_tg_app/static:ro
      - ./shop_tg_app/media:/app/www/shop_tg_app/media:ro
      - ./shop_tg_app/logs:/app/www/shop_tg_app/logs
  ##################################################################
  # Redis ( using port 6379 )
  ##################################################################
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - tg-shop-net

volumes:
  postgres_data:

networks:
  tg-shop-net:
    driver: bridge