# Generated by Django 5.2 on 2025-05-06 14:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'size')},
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_photos/')),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10000)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='shop.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
