# Generated by Django 5.2 on 2025-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='products_photos_preview/'),
        ),
    ]
