# Generated by Django 5.2 on 2025-05-18 19:55

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productphoto_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to='products_photos/', validators=[shop.validators.validate_jpg_image]),
        ),
    ]
