# Generated by Django 5.2.3 on 2025-07-03 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
